root = "."
tmp_dir = "tmp-api"

[build]
  bin = "./tmp-api/api"
  cmd = "go build -o ./tmp-api/api ./cmd/api"
  delay = 500
  exclude_dir = ["tmp", "tmp-api", ".git"]
  include_ext = ["go"]
  kill_delay = "500ms"
  send_interrupt = true
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
