-- Historical: this added server_members.last_status and an index on it.
--
-- The column cached each player's newest status so the server log embed footer
-- could count connected players. The footer was removed, taking its only
-- reader with it, and 000031 dropped the column.
--
-- The statements are gone rather than guarded. The startup runner replays every
-- up file on every boot: ADD COLUMN IF NOT EXISTS is not a no-op once a column
-- has been dropped, and the standalone CREATE INDEX on last_status would fail
-- outright - the same failure 000015's index on member_id shipped.
--
-- Kept as a file so the sequence has no hole and the history stays readable.
