-- Historical: this added server_members.character_name and backfilled it from
-- members.character_name, which 000027 then dropped.
--
-- 000030 dropped this column too. Beside player_name, which the webhook reports
-- on every event, a curated name was the same value kept twice: most of the
-- backfilled rows were the reported name retyped, and the ones that were not
-- drifted from it with nothing to reconcile them.
--
-- The statements are gone rather than guarded. The startup runner replays every
-- up file on every boot, and ADD COLUMN IF NOT EXISTS is not a no-op once the
-- column has been dropped: every boot would add it back and 000030 would drop
-- it again. The backfill it carried read members.character_name, which no
-- longer exists at all.
--
-- Kept as a file so the sequence has no hole and the history stays readable.
